version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    depends_on:
      - es
    container_name: kb
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
  snpweb:
    build: .
    #image: fallen576/snp:latest
    depends_on:
      - es
    ports:
      - 8080:8080
volumes:
  esdata1:
    driver: local